engines:
  duplications:
    enabled: false
    config:
      languages:
        - javascript
languages:
  JavaScript: true
eslint:
  enabled: true
fixme:
  enabled: true
exclude_paths:
- .travis.yml
- .eslintrc
- jasmine/assets
- jasmine/lib