engines:
  duplication:
    enabled: true
languages:
  JavaScript: true
eslint:
  enabled: true
fixme:
  enabled: true
exclude_paths:
- "lib/es5/simplenumbers.js"
- .npmignore
- .travis.yml
- .eslintrc.json
- .babelrc
- tests/test.js
- jasmine/assets
- jasmine/lib