engines:
  duplication:
    enabled: true
languages:
  JavaScript: true
eslint:
  enabled: true
fixme:
  enabled: true
ratings:
  paths:
  - "public/js/*"
exclude_paths:
- .travis.yml
- .eslintrc
- jasmine/assets/*
- jasmine/lib/**/*